Array Slicing & Skewness

In [1]:
import numpy as np

1. 1D Array Slicing
Given the following 1D array:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
1. Extract elements from index 2 to 6 (exclusive of 6).
2. Extract every second element from the entire array.
3. Reverse the entire array using slicing.
4. Extract the last 4 elements.
5. Extract elements from index 1 to 7 with a step of 2.

In [2]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
#1. Extract elements from index 2 to 6 (exclusive of 6).
arr[2:6]

array([30, 40, 50, 60])

In [6]:
#2. Extract every second element from the entire array.
arr[::2]

array([10, 30, 50, 70, 90])

In [7]:
#3. Reverse the entire array using slicing.
arr[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

In [9]:
#4. Extract the last 4 elements.
arr[-4:]

array([60, 70, 80, 90])

In [13]:
#5. Extract elements from index 1 to 7 with a step of 2.
arr[1:7:2]

array([20, 40, 60])

2. 2D Array Slicing
Given the following 2D array:
arr_2d = np.array([
[1, 2, 3, 4, 5],
[6, 7, 8, 9, 10],
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20]
])
1. Extract the entire second row.
2. Extract the entire third column.
3. Extract every alternate column from all rows.
4. Extract the bottom-right 2×2 sub-array.

In [15]:
arr_2d = np.array([
[1, 2, 3, 4, 5],
[6, 7, 8, 9, 10],
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20]
])
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
#Extracting 2nd row
arr_2d[1]

array([ 6,  7,  8,  9, 10])

In [18]:
#Extracting 3rd column
arr_2d[:,2]

array([ 3,  8, 13, 18])

In [20]:
#3. Extract every alternate column from all rows.
arr_2d[:,0::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

In [23]:
#4. Extract the bottom-right 2×2 sub-array.
arr_2d[-2:, -2:]

array([[14, 15],
       [19, 20]])

3. 3D Array Slicing
Given the following 3D array:
arr_3d = np.arange(1, 25).reshape(2, 3, 4)
# Shape: (2, 3, 4)
1. Extract the second row from every 2D slice.
2. Extract the last column from every 2D slice.
3. Extract a sub-array of shape (2, 2, 2) from the top-left corner of each 2D slice.
4. Extract elements of all corners only 0 row and last row

In [26]:
arr_3d = np.arange(1, 25).reshape(2, 3, 4)
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [28]:
#1. Extract the second row from every 2D slice.
arr_3d[0:,1]

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [29]:
#2. Extract the last column from every 2D slice.
arr_3d[:,:,-1]

array([[ 4,  8, 12],
       [16, 20, 24]])

In [30]:
#3. Extract a sub-array of shape (2, 2, 2) from the top-left corner of each 2D slice.
arr_3d[:,:2,:2]


array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]])

In [39]:
#4. Extract elements of all corners only 0 row and last row
arr_3d[:, [0, -1], :][:, :, [0, -1]]

array([[[ 1,  4],
        [ 9, 12]],

       [[13, 16],
        [21, 24]]])

4. Skewness Calculation of Raw Data
Dataset:
data1 = [12, 15, 14, 10, 18, 20, 22, 25, 13, 17, 19, 21, 16, 14, 23]
data2 =[5, 7, 8, 9, 10, 12, 15, 18, 22, 30, 45, 60]


In [44]:
data1 = [12, 15, 14, 10, 18, 20, 22, 25, 13, 17, 19, 21, 16, 14, 23]
data2 =[5, 7, 8, 9, 10, 12, 15, 18, 22, 30, 45, 60]

In [53]:
import scipy
from scipy import stats

In [54]:
stats.skew(data1)

np.float64(0.12803035988246822)

In [55]:
stats.skew(data2)

np.float64(1.3431755308450162)