1. Create a 1D NumPy array containing the numbers from 10 to 50 (inclusive) with a step of 5.
● Print the entire array.
● Access and print the 3rd element.
● Access and print the last element using negative indexing.

In [38]:
import numpy as np

In [39]:
a1= np.arange(10,50,2)
print(a1)

print("3rd element:",a1[2])
print("Last Element:",a1[-1])

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
3rd element: 14
Last Element: 48


2. Create a 2D NumPy array of shape (3, 4) filled with numbers from 1 to 12 (row-wise).
● Print the entire array.
● Access and print the element at row 1, column 2.

In [40]:
a2=np.arange(1,13).reshape(3,4)

print("2D Array:\n",a2)

print("\nELement at row 1  column 2:",a2[0,1])
# print(a2[0,1])


2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

ELement at row 1  column 2: 2


3. Create a 3D NumPy array of shape (2, 3, 4) filled with sequential numbers starting from
1.
● Print the entire array.
● Access and print the element at depth 0, row 1, column 2.


In [41]:
a3=np.arange(1,25).reshape(2,3,4)
print(a3)

print("\nThe element at depth 0, row 1, column 2: ",a3[0][0][1])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

The element at depth 0, row 1, column 2:  2


4. Calculate mean median Variance, Standard deviation of
a. 12,32,56,32,87,65,45,32,12,32
b. 34,56,87,98,12,43,21,45,67,87,22,43

In [42]:
#a

a = np.array([12, 32, 56, 32, 87, 65, 45, 32, 12, 32])

print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Variance:", np.var(a))
print("Standard Deviation:", np.std(a))

Mean: 40.5
Median: 32.0
Variance: 493.65
Standard Deviation: 22.21823575354263


In [43]:
b=np.array([34,56,87,98,12,43,21,45,67,87,22,43])
print("Mean: ",np.mean(b))
print("Median: ",np.median(b))
print("Variance: ",np.var(b))
print("Standard Deviation:",np.std(b))

Mean:  51.25
Median:  44.0
Variance:  733.0208333333334
Standard Deviation: 27.074357486990035
